### ISSUE TITLE
会不会是pjax问题

### ISSUE THREAD

**Issue by wang4386** [ShangJixin/Typecho-Plugin-superLink#1]
我在使用Typecho1.2.1+handsome9.2.1并且开启PJAX的情况下，从首页进入文章，github的链接卡片不加载仓库信息，需要刷新文章页面才会加载仓库信息，是不是pjax的问题?另外可以适配一下gitee和gitlab吗？

**Comment by ShangJixin** [comment]
确实是 GitHub 卡片未设计回调函数的原因，导致 pjax 出问题，这个好修。
Gitee 和 Gitlab 可以提上日程，看看能找时间更新一下吧。

**Comment by ShangJixin** [comment]
https://github.com/ShangJixin/Typecho-Plugin-superLink/releases/tag/V1.6

已发布新版V1.6。新增了回调函数，回调函数为`superLink();`。

同时也已适配Gitee的解析。

GitLab因私有部署的非常多，且付费，解析难以实现，故放弃对GitLab的适配。
